version: '2.2'
services:
  app:
    build: .
    command: npm run start:watch
    ports:
      - 3000
    environment:
      - EXTERNAL_SERVICE_HOST=http://www.google.com
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
